baseURL = 'https://saibamidori.moe/'
languageCode = 'zh-CN'
title = 'Project for Saiba Midori'
theme = 'midori'

disableKinds = ["categories", "taxonomy", "term", "RSS"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # 设置为 true 以允许在 Markdown 文件中直接写 HTML 标签
      unsafe = true
      