baseURL = 'https://saibamidori.moe/'
defaultContentLanguage = 'zh-CN'
defaultContentLanguageInSubdir = false
theme = 'midori'

[languages]
  [languages.zh-CN]
    languageCode = 'zh-CN'
    languageName = '简体中文'
    title = 'Project for Saiba Midori'
    weight = 1

  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    title = 'Project for Saiba Midori'
    weight = 2

disableKinds = ["taxonomy", "term"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # 设置为 true 以允许在 Markdown 文件中直接写 HTML 标签
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[params]
  backgroundImage = 'https://static.saibamidori.moe/img/29131.png'

  footerHTML = """
  <p>Copyright &copy; 2026 <a href="https://github.com/gytxtx">KFACBT</a>. All rights reserved.</p>
  <p style="margin-left: 0.5rem;"><a href="https://github.com/Saiba-Midori-Projects/SaibaMidori.moe">在 GitHub 上查看源代码</a></p>
  """
